### ISSUE TITLE
code is incomplete, and some errors are need to be fixed

### ISSUE THREAD

**Issue by leeeizhang** [dawenzi098/SFL-Structural-Federated-Learning#3]
Thanks for your insipring work. I meet some issues when I follow your README.md for code running:
1. I cannot find the `generate_training_data.py` in current repo, could you upload this for data generation;
2. Something wrong in pooling shape when I follow `python main.py --dataset cifar10 --com_round 20 --shards 5 --agg graph_v3`:
```
Prepare data and model...
Files already downloaded and verified
Files already downloaded and verified
Parameter holders
Namespace(adj_data='data/sensor_graph/adj_mx.pkl', adjalpha=3, adjbeta=0.05, agg='graph_v3', batch_size=128, bn=0, cl=1, client_epochs=20, client_frac=1, clients=100, clip=5, com_round=20, conv_channels=32, dataaug=0, dataset='cifar10', debug=0, deep=0, device=device(type='cuda', index=1), dilation_exponential=1, dp=0.005, dropout=0.3, edge_frac=1, end_channels=128, epoch=10, epsilon=1, evalall=0, gc_epoch=10, gcn_depth=2, hidden=[10, 20, 320, 50], in_dim=2, kernel_num=9, kernel_sizes='3,4,5', layers=3, logDir='./log/cifar10-graph_v3-20-20-default.txt', lr=0.01, max_pool='True', node_dim=40, norm='batch_norm', num_channels=1, num_classes=10, num_filters=32, num_split=1, num_thread=5, ord=2, print_every=100, propalpha=0.05, reg=1, residual_channels=32, rnn_hidden=64, runs=10, save='./save/', seed=1, seq_in_len=12, seq_out_len=12, serveralpha=1, serverbeta=0.3, shards=5, skip_channels=64, sm='full', step_size1=2500, step_size2=100, subgraph_size=30, unequal=0, valid_freq=1, weight_decay=0.0001)
Number of model parameters is 2440256
Start Training...
Traceback (most recent call last):
  File "main.py", line 126, in <module>
    main(option)
  File "main.py", line 47, in main
    outputs = engine.run()
  File "/mnt/data1/zhanglei/projects/SFL-Structural-Federated-Learning-main/federated.py", line 48, in run
    output = self.client_run()
  File "/mnt/data1/zhanglei/projects/SFL-Structural-Federated-Learning-main/federated.py", line 67, in client_run
    stats = self.batch_run(True, opt.step)
  File "/mnt/data1/zhanglei/projects/SFL-Structural-Federated-Learning-main/federated.py", line 106, in batch_run
    output = self.model(batch)
  File "/home/zhanglei/software/python3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data1/zhanglei/projects/SFL-Structural-Federated-Learning-main/BResidual.py", line 28, in forward
    self.cache[n] = getattr(self, n)(*[self.cache[x] for x in i])
  File "/home/zhanglei/software/python3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhanglei/software/python3/lib/python3.8/site-packages/torch/nn/modules/pooling.py", line 162, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "/home/zhanglei/software/python3/lib/python3.8/site-packages/torch/_jit_internal.py", line 405, in fn
    return if_false(*args, **kwargs)
  File "/home/zhanglei/software/python3/lib/python3.8/site-packages/torch/nn/functional.py", line 718, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (256x4x4). Calculated output size: (256x0x0). Output size is too small
```

**Comment by JackqqWang** [comment]
The same error

**Comment by xiaoying218** [comment]
same error

**Comment by 18205123** [comment]
same error

**Comment by dawenzi098** [comment]
This error is due to the update of PyTorch.

opt the last layer(nn.MaxPooling2D) parameter would solve the error. 

Code has been update for this.(from 8 to 2)
